######################################################################
# Automatically generated by qmake (3.1) Mon Apr 14 15:46:44 2025
######################################################################
QT += core gui widgets network 
TEMPLATE = app
TARGET = seti_net
INCLUDEPATH += .

CONFIG += c++17

SOURCES += src/source.cpp

unix:!macx: LIBS += -lqtermwidget5
