# Функция для настройки режимов сборки
function(setup_build_directories)
  if (CMAKE_BUILD_TYPE STREQUAL "Release")
    message("Release build")
    add_compile_definitions(QT_NO_DEBUG_OUTPUT)
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${PROJECT_ROOT_DIR}/Build/Release" PARENT_SCOPE)
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${PROJECT_ROOT_DIR}/Build/Release/lib" PARENT_SCOPE)
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${PROJECT_ROOT_DIR}/Build/Release/lib" PARENT_SCOPE)
  elseif (CMAKE_BUILD_TYPE STREQUAL "Debug")
    message("Debug build")
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${PROJECT_ROOT_DIR}/Build/Debug" PARENT_SCOPE)
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${PROJECT_ROOT_DIR}/Build/Debug/lib" PARENT_SCOPE)
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${PROJECT_ROOT_DIR}/Build/Debug/lib" PARENT_SCOPE)
  endif()
endfunction()